version: "3"

networks:
  pgqf_net:
    ipam:
      driver: default
      config:
        - subnet: 172.21.1.0/24

services:
  validator:
    build:
      context: ../../../
      dockerfile: ./sdk/examples/pgqf/Dockerfile
    environment:
      - RUST_LOG=info,wasmer_compiler_cranelift::translator::func_translator=error
    command: ./anoma-devnode
    networks:
      pgqf_net:
        ipv4_address: 172.21.1.2

  solver:
    build:
      context: ../../../
      dockerfile: ./sdk/examples/pgqf/Dockerfile
    environment:
      - RUST_LOG=info,wasmer_compiler_cranelift::translator::func_translator=error
    command: ./pgqf-solver --peer 172.21.1.2:44668
    networks:
      pgqf_net:
        ipv4_address: 172.21.1.3
    depends_on:
      validator:
        condition: service_started

  client:
    build:
      context: ../../../
      dockerfile: ./sdk/examples/pgqf/Dockerfile
    environment:
      - RUST_LOG=info,wasmer_compiler_cranelift::translator::func_translator=error
    command: ./pgqf-client --peer 172.21.1.3:44667
    networks:
      pgqf_net:
        ipv4_address: 172.21.1.4
    depends_on:
      solver:
        condition: service_started
